In [10]:
# Imports

import numpy as np
import matplotlib.pyplot as plt

%matplotlib ipympl



In [11]:
## Echauffement

a = np.array([1,2,3])

#1) a est de forme (3) => a[:,None] est de forme (3,1)
# a est de forme (3) => a[None,:] est de forme (1,3)

#2) a[:, None] - a[None, :] => de forme (3,3) 
# on obtient le résultat de : [[1,1,1],[2,2,2],[3,3,3]] - [[1,2,3],[1,2,3],[1,2,3]]
print(a[:, None] - a[None, :])
print(np.array([[1,1,1],[2,2,2],[3,3,3]]) - np.array([[1,2,3],[1,2,3],[1,2,3]]))

# On a bien la même chose, on généralise : 
# RES[i,j]=a[i]-a[j]


#3) b est de forme (2,3)
# => b[:,None,:] est de forme (2,1,3)
# => b[:,:,None] est de forme (2,3,1)
# 
# => RES = b[:,None,:] - b[:,:,None] est de forme (2,3,3)
#
# RES[i,j,k] = b[:,None,:][i][1][k] - b[:,:,None][i][j][1]
#            = b[i][k] - b[i][j]



[[ 0 -1 -2]
 [ 1  0 -1]
 [ 2  1  0]]
[[ 0 -1 -2]
 [ 1  0 -1]
 [ 2  1  0]]
