In [10]:
# Imports

import numpy as np
import matplotlib.pyplot as plt

%matplotlib ipympl



In [11]:
## Echauffement

a = np.array([1,2,3])

#1) a est de forme (3) => a[:,None] est de forme (3,1)
# a est de forme (3) => a[None,:] est de forme (1,3)

#2) a[:, None] - a[None, :] => de forme (3,3) 
# on obtient le résultat de : [[1,1,1],[2,2,2],[3,3,3]] - [[1,2,3],[1,2,3],[1,2,3]]
print(a[:, None] - a[None, :])
print(np.array([[1,1,1],[2,2,2],[3,3,3]]) - np.array([[1,2,3],[1,2,3],[1,2,3]]))

# On a bien la même chose, on généralise : 
# RES[i,j]=a[i]-a[j]


#3) b est de forme (2,3)
# => b[:,None,:] est de forme (2,1,3)
# => b[:,:,None] est de forme (2,3,1)
# 
# => RES = b[:,None,:] - b[:,:,None] est de forme (2,3,3)
#
# RES[i,j,k] = b[:,None,:][i][1][k] - b[:,:,None][i][j][1]
#            = b[i][k] - b[i][j]



[[ 0 -1 -2]
 [ 1  0 -1]
 [ 2  1  0]]
[[ 0 -1 -2]
 [ 1  0 -1]
 [ 2  1  0]]


In [ ]:
## Initialisation aléatoire

# les bornes pour le tirage au sort initial
mass_max = 3.
    
x_min, x_max = -10., 10.
y_min, y_max = -10., 10.

speed_max = 1.



def init_problem(N):
    """
    retourne un tuple masses, positions, speeds
    de formes resp.   (N,)    (2, N)     (2, N)
    tiré au sort dans les bornes définies ci-dessus
    """
    masses=np.random.uniform(0, mass_max, (N,))
    positions=np.random.uniform(np.array([[x_min],[y_min]]), np.array([[x_max],[y_max]]), (2,N))
    speeds=np.random.uniform(0, speed_max, (2,N))

    return masses, positions, speeds

print(init_problem(5))

[[-8.7274455  -0.15257029  7.51510337  9.25264224 -7.80538625]
 [-2.58140434  3.86553398 -8.79824311 -7.6680646  -8.31081617]]
